eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址
      
  rabbitmq:     # 配置RabbitMQ
  host: localhost
  port: 5672
  username: guest
  password: guest       
      